### ISSUE TITLE
Override config values breaks migration

### ISSUE THREAD

**Issue by delmicio** [akaunting/setting#13]
Hi, I've just tries to re-install my laravel project on another computer and when I attemp to run `artisan migrate` I got an error:
```
php artisan migrate

In Connection.php line 664:

 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.settings' doesn't exist (SQL: select * from `settings`)


In PDOConnection.php line 79:

 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.settings' doesn't exist


In PDOConnection.php line 77:

 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.settings' doesn't exist
```

To make my migrations work I edited my `config/setting.php` file and removed the 'override' setting.

**Comment by denisdulici** [comment]
Emanuel, make sure that the settings table is created first by editing the migration file name.

**Comment by delmicio** [comment]
@denisdulici that does not solve the issue.

**Comment by delmicio** [comment]
If anyone faces this issue I've found a hack around it. 
You sould now have the override option when doing the settings table migration. Si I added a try catch at the beggining of the config.

```PHP
<?php

try {
    setting('a');
} catch (Exception $e) {
    // not migrated yet
    return [];
}

return [
    ...
    ...
```

Hope you guys can fix this on your next release.
