### ISSUE TITLE
Cache option

### ISSUE THREAD

**Issue by Cannonb4ll** [akaunting/setting#30]
Will it be possible to cache settings so no queries are executed in the future?

**Comment by denisdulici** [comment]
It would be a good feature, will definitely consider.

**Comment by lorenlang** [comment]
I'll second the idea for a cache but would suggest making it optional.  Or at a minimum, provide a method that always gets the latest value from the DB.  Some settings (lock flags, next available ID number, etc.) could change after the value is read into the cache and you always want the most up to date version.

**Comment by n-osennij** [comment]
+1

**Comment by mojtabaahn** [comment]
would you like PRs for this?

**Comment by denisdulici** [comment]
For sure, PR is always welcome.

**Comment by denisdulici** [comment]
This has been added in 1.1 version.
