### ISSUE TITLE
Feature Request: Allow global overrides

### ISSUE THREAD

**Issue by DeftNerd** [akaunting/setting#4]
Rather than manually specifying overrides, it would be nice to be able to just set a "fallback" boolean in the setting config file. 

If a `setting('value')` isn't set, and the `fallback` boolean is set to `true`, then the package would check for `config('value')` and return that value if it is set. If `config('value')` isn't set, then it would return null.

**Comment by denisdulici** [comment]
It depends. I may not want to override some/most of config and in such a case must manually specify the overrides to skip.
