### ISSUE TITLE
Do not delete items with null values from database!

### ISSUE THREAD

**Issue by 4n70w4** [akaunting/setting#44]
Incorrect condition!

https://github.com/akaunting/setting/blob/master/src/Drivers/Database.php#L171

Test:
```
$insertData[$key] = null;
isset($insertData[$key]); // === false
```

Better use array_key_exists() instead isset()
Because null is cortrect value!

https://github.com/akaunting/setting/issues/43

**Comment by denisdulici** [comment]
Feel free to contribute.

**Comment by 4n70w4** [comment]
@denisdulici why did you close? Issue not resolved! dislike for you!
