### ISSUE TITLE
Extra Columns

### ISSUE THREAD

**Issue by AEK-BKF** [akaunting/setting#5]
Hi,

Thanks for this nice package !
Please, where should I put this code to enable multi users settings :
`setting()->setExtraColumns(['user_id' => Auth::user()->id]);`
and How can I retrieve user's settings : 
`$value = $user->settings->key;`

Thanks.

**Comment by denisdulici** [comment]
See line 34-35:

https://github.com/akaunting/akaunting/blob/master/app/Http/Middleware/ApiCompany.php#L34

Then just use `$value = setting('key');`

**Comment by Braunson** [comment]
@denisdulici Any way to do this with settings on two fronts.

1. Team
2. User
