### ISSUE TITLE
config required_extra_columns

### ISSUE THREAD

**Issue by thewebartisan7** [akaunting/setting#52]
What is purpose of config required_extra_columns here https://github.com/akaunting/setting/blob/master/src/Config/setting.php#L98

I see that we must add the same extra columns in this config that we add here:

`setting()->setExtraColumns(['user_id' => Auth::user()->id]);`

example:

```
    'required_extra_columns' => [
        'user_id'
    ],
```

Then I see that this checkExtraColumns() here https://github.com/akaunting/setting/blob/master/src/Contracts/Driver.php#L220 is called many times in the code, but why? Is not documented this part.

Also why not make this checkExtraColumns just once, and store value for other use?

Thanks!

**Comment by denisdulici** [comment]
Fields in `required_extra_columns` must be set before operating with setting.
