### ISSUE TITLE
Method not found all()

### ISSUE THREAD

**Issue by pacoorozco** [akaunting/setting#55]
Hi,

I'm using your wonderful package in my Laravel 6.x application. Reviewing the issues in [Scrutinizer](https://scrutinizer-ci.com/g/pacoorozco/ssham/issues/add-tests/files/app/Http/Controllers/SettingsController.php?orderField=path&order=asc&honorSelectedPaths=0) I've seen that it is not able to find some methods. 

In fact, if i try to use Setting::all() instead, my IDE is unable to find the class... *Can you confirm that it's a fake positive?*

Thanks in advance

**Comment by denisdulici** [comment]
It works fine for me.
