### ISSUE TITLE
Argument 1 passed to Akaunting \ Setting \ Support \ Arr :: get () 

### ISSUE THREAD

**Issue by vdkar** [akaunting/setting#66]
After upgrading to version 1.2 I got the error

Argument 1 passed to Akaunting \ Setting \ Support \ Arr :: get () must be of the type array, null given, called in \ site \ vendor \ akaunting \ setting \ src \ Contracts \ Driver.php on line 64

I use it in my blade
@setting("setting.else.code_head")

php7.4, laravel7

How to be?

**Comment by denisdulici** [comment]
Can you try to change that line with the following:

```php
return Arr::get((array) config('setting.fallback'), $key);
```

**Comment by vdkar** [comment]
Works
