### ISSUE TITLE
Laravel 8.x: Undefined property: Akaunting\Setting\Manager::$app

### ISSUE THREAD

**Issue by fabianpnke** [akaunting/setting#68]
Hi,

I've tried to play around with Laravel 8.x.

When I'm trying to access a setting inside Blade

```html
<a class="dropdown-item" href="{{ setting('topbar.phone.link') }}">
```
I'm getting the error message for the following line of code:

```
Undefined property: Akaunting\Setting\Manager::$app
vendor/akaunting/setting/src/Manager.php:57

public function createDatabaseDriver()
    {
        $connection = $this->app['db']->connection(config('setting.database.connection'));
```

The Upgrade Guide for Laravel 8.x says:

Manager $app Property
Likelihood Of Impact: Low

The previously deprecated `$app` property of the `Illuminate\Support\Manager` class has been removed. If you were relying on this property, you should use the `$container` property instead.

Thanks and regards
Fabian

**Comment by dacoto97** [comment]
@fabianpnke  I have created this PR #69 in which it is solved!

**Comment by dacoto97** [comment]
### ⚠️  Library not compatible with laravel 8.x or higher. ⚠️
As the library cannot be updated, it is **discarded** for versions of laravel **8.x or higher**.
