### ISSUE TITLE
Feature: Include fallback with all

### ISSUE THREAD

**Issue by dalholm** [akaunting/setting#70]
It would be nice to be able to call `Setting::withFallback()->get()`

Why? 
I have a UI with all the settings loaded via ajax and vue, the user can change them if they want. But as default  all settings are loaded with the fallbacks.

I have solved it my self, but maybe something the package wants to add?

**Comment by TechTailor** [comment]
Please feel free to open a PR for it. If it has good use-case, it will surely get merged and be helpful to others as well.

Thanks. 
-TT

**Comment by dalholm** [comment]
Sorry for the late reply, i have been working on another project. 

I have submitted a PR #79
