### ISSUE TITLE
Multi-tenant issue

### ISSUE THREAD

**Issue by JurjenRoels** [akaunting/setting#71]
Hi,

I have an issue where if I change the setExtraColumns, the update is ignored. See attached tinker

>>> setting()->all()
=> []
>>> setting()->getExtraColumns()
=> []
>>> setting()->setExtraColumns(['site_id' => 2])
=> null
>>> setting()->all()
=> [
     "languages" => [
       "nl",
     ],
     "types" => [
       "normal",
       "contact",
     ],
     "account" => "prod2",
   ]
>>> setting()->getExtraColumns()
=> [
     "site_id" => 2,
   ]
>>> setting()->setExtraColumns(['site_id' => 1])
=> null
>>> setting()->getExtraColumns()
=> [
     "site_id" => 1,
   ]
>>> setting()->all()
=> [
     "languages" => [
       "nl",
     ],
     "types" => [
       "normal",
       "contact",
     ],
     "account" => "prod2",
   ]
>>> exit
Exit:  Goodbye
art tinker         
Psy Shell v0.10.4 (PHP 7.4.10 — cli) by Justin Hileman
>>> setting()->setExtraColumns(['site_id' => 1])
=> null
>>> setting()->all()
=> [
     "languages" => [
       "nl",
     ],
     "types" => [
       "normal",
     ],
     "account" => "test2",
   ]
>>> setting()->setExtraColumns(['site_id' => 2])
=> null
>>> setting()->all()
=> [
     "languages" => [
       "nl",
     ],
     "types" => [
       "normal",
     ],
     "account" => "test2",
   ]
>>>

**Comment by JurjenRoels** [comment]
When I add:

$this->loaded = false

to setExtraColumns in Database.php the problem is solved.

**Comment by denisdulici** [comment]
Add the following lines after setting the extra column:

```php
setting()->setExtraColumns(['site_id' => 1]);
setting()->forgetAll();
setting()->load(true);
```
