### ISSUE TITLE
Forget not working

### ISSUE THREAD

**Issue by fixer112** [akaunting/setting#72]
setting()->forget('foo'); does not work and setting()->forget('foo')->save() gives Call to a member function save() on null ;

**Comment by TechTailor** [comment]
For some reason I never actually had the need to use the forget function even though I have been using this package for 2 years. 

Will look into it and see what the issue might be. 

-TT

**Comment by TechTailor** [comment]
Oh wait, just noticed the issue, you are chaining the methods. That wont work. 

using setting()->forget('foo') will remove the key from the array but not persist it, you need to call setting()->save() afterwords to persist the change. You cannot chain them.

```
setting()->forget('foo');
setting()->save();
```

-TT

**Comment by fixer112** [comment]
Thanks, figured it out.
