### ISSUE TITLE
how probleam  in  get with extra cloumn

### ISSUE THREAD

**Issue by vahidalvandi** [akaunting/setting#75]
hi save this setting with this code work fine ! but i cant find document about get with extra column !! please show a sample

```
    setting()->setExtraColumns(['user_id' => Auth::user()->id]);

        setting()->set('notification.type', $request->sms_default);

        setting()->save();
```

**Comment by denisdulici** [comment]
After setting the extra column, every get/set is based on that.

**Comment by vahidalvandi** [comment]
not work correctly
