### ISSUE TITLE
It would be great if we could store more than just string values in the database.

### ISSUE THREAD

**Issue by nesh-ua** [akaunting/setting#76]
I think we can add type of value and convert from string to this type when get this value. this means that when i set number, i will get number. if i set boolean i will get boolean...

**Comment by TechTailor** [comment]
Can you explain a bit more about what exactly you want to achieve? Right now if you store a value as boolean, you will retrieve the same boolean value, ex:

```settings()->set('active', true);```

and use it as:
```
if(settings()->get('active')
// do something
```

just don't add the "" on the value and it will act as boolean. 

Trying to store the type of a key and create a way to convert said type will just create unnecessary complexities that you don't need. Alas if you have a good use-case of why you need on-the-fly type conversation from string to other types, do share.

-TT

**Comment by nesh-ua** [comment]
Ok, i will check it. What about other types? int, array?

**Comment by TechTailor** [comment]
Hmm... Can you provide an actual use case example where you would want to explicitly store and use different types from the settings table itself and it's beneficial. Thanks.

-TT
