### ISSUE TITLE
Allowed memory size

### ISSUE THREAD

**Issue by soroosh-e** [akaunting/setting#77]
Hi
This package cause this problem while installing:
Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes)
I have this issue only with this package.
I know that I can run composer update to solve this problem, but It effects on all next packages that I want to install. and all of installations face this problem after having this package.

**Comment by TechTailor** [comment]
This is a composer related issue and not cause of this package. 

You can refer to quick fixes given for it in this thread to resolve it - https://stackoverflow.com/questions/49212475/composer-require-runs-out-of-memory-php-fatal-error-allowed-memory-size-of-161

-TT
